/////// Members Section

### Get All Members
GET http://localhost:3000/members

### Get Single Member
GET http://localhost:3000/members/679187ee228060f5d63da6e3

### Create Member
POST http://localhost:3000/members HTTP/1.1
Content-Type: application/json

{
  "name": "John Doe",
  "age": 25,
  "membershipType": "Premium",
  "joinDate": "2025-02-10",
  "contactNumber": "123-456-7890",
  "coachId": "6791ab2ca1a0e59ed8e8f5e0"
}

### Update Member
PUT http://localhost:3000/members/6791ae26d0cfd9b0ef6b9979
Content-Type: application/json

{
  "name": "John Doe",
  "age": 26,
  "membershipType": "Gold",
  "joinDate": "2025-03-10T10:00:00Z",
  "contactNumber": "123-456-7890",
  "coachId": "6791ab2ca1a0e59ed8e8f5e0"
}

### Delete Member
DELETE http://localhost:3000/members/6791ae26d0cfd9b0ef6b9979


/////// Coaches Section

### Create Coach
POST http://localhost:3000/coaches HTTP/1.1
Content-Type: application/json

{
  "name": "Dr. John Smith",
  "specialty": "Strength Training",
  "experienceYears": 5,
  "contactNumber": "555-1234"
}

### Update Coach
PUT http://localhost:3000/coaches/6791ab2ca1a0e59ed8e8f5e0
Content-Type: application/json

{
  "name": "Dr. John Smith",
  "specialty": "Cardio Training",
  "experienceYears": 6,
  "contactNumber": "555-1234"
}

### Delete Coach
DELETE http://localhost:3000/coaches/6791ab2ca1a0e59ed8e8f5e0
